/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-06-17 05:00:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bottom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/E/Sist/Class/Workspace/Spring%20Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SENTI/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716191238840L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://d13fzx7h5ezopb.cloudfront.net/fonts/font.css\">\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("        href=\"https://cdn-resource-microservice.29cm.co.kr/product/_next/static/css/4e0d66812cb47237.css\" data-n-g=\"\">\r\n");
      out.write("    <style data-emotion=\"css-global\" data-s=\"\">\r\n");
      out.write("        ol,\r\n");
      out.write("        li {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        a {\r\n");
      out.write("            -webkit-text-decoration: none;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("        body,\r\n");
      out.write("        input,\r\n");
      out.write("        select,\r\n");
      out.write("        textarea,\r\n");
      out.write("        button,\r\n");
      out.write("        a {\r\n");
      out.write("            -webkit-text-size-adjust: none;\r\n");
      out.write("            font-family: 'campton', 'Apple SD Gothic Neo', NanumBarunGothic, '나눔바른고딕', Malgun Gothic, '맑은 고딕', dotum, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type='search']::-webkit-search-decoration,\r\n");
      out.write("        input[type='search']::-webkit-search-cancel-button,\r\n");
      out.write("        input[type='search']::-webkit-search-results-button,\r\n");
      out.write("        input[type='search']::-webkit-search-results-decoration {\r\n");
      out.write("            -webkit-appearance: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        html,\r\n");
      out.write("        body {\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("    <style>\r\n");
      out.write("        .css-jmbq56 {\r\n");
      out.write("            margin-bottom: 6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-1lo70d {\r\n");
      out.write("            min-width: 900px;\r\n");
      out.write("            padding: 0 50px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-6936h5 {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            display: -webkit-box;\r\n");
      out.write("            display: -webkit-flex;\r\n");
      out.write("            display: -ms-flexbox;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            -webkit-flex-direction: column;\r\n");
      out.write("            -ms-flex-direction: column;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: var(--ruler-scale-dimension-100);\r\n");
      out.write("            -webkit-align-items: flex-start;\r\n");
      out.write("            -webkit-box-align: flex-start;\r\n");
      out.write("            -ms-flex-align: flex-start;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-dbdgx9 {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-family: var(--ruler-semantic-typography-text-xl-bold-font-family);\r\n");
      out.write("            font-weight: var(--ruler-semantic-typography-text-xl-bold-font-weight);\r\n");
      out.write("            line-height: var(--ruler-semantic-typography-text-xl-bold-line-height);\r\n");
      out.write("            font-size: var(--ruler-semantic-typography-text-xl-bold-font-size);\r\n");
      out.write("            color: var(--ruler-semantic-color-text-primary);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-3x9huk {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-family: var(--ruler-semantic-typography-text-s-medium-font-family);\r\n");
      out.write("            font-weight: var(--ruler-semantic-typography-text-s-medium-font-weight);\r\n");
      out.write("            line-height: var(--ruler-semantic-typography-text-s-medium-line-height);\r\n");
      out.write("            font-size: var(--ruler-semantic-typography-text-s-medium-font-size);\r\n");
      out.write("            color: var(--ruler-semantic-color-text-tertiary);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-k008qs {\r\n");
      out.write("            display: -webkit-box;\r\n");
      out.write("            display: -webkit-flex;\r\n");
      out.write("            display: -ms-flexbox;\r\n");
      out.write("            display: flex;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-bs7ejj {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            width: 94px;\r\n");
      out.write("            margin-left: 4px;\r\n");
      out.write("            padding-left: 14px;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            line-height: 30px;\r\n");
      out.write("            color: var(--ruler-semantic-color-text-on-color);\r\n");
      out.write("            background: var(--ruler-semantic-color-fill-primary);\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-bs7ejj:first-of-type {\r\n");
      out.write("            margin-left: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .css-1o3s5tf {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            right: 10px;\r\n");
      out.write("            width: 4px;\r\n");
      out.write("            height: 8px;\r\n");
      out.write("            margin-top: -4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-1o3s5tf path {\r\n");
      out.write("            stroke: #a0a0a0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-1tfgiui {\r\n");
      out.write("            width: 42px;\r\n");
      out.write("            height: 80px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            right: 10px;\r\n");
      out.write("            width: 4px;\r\n");
      out.write("            height: 8px;\r\n");
      out.write("            margin-top: -4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-1tfgiui path {\r\n");
      out.write("            stroke: #a0a0a0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-1xit630 {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-1y0tu78 {\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 30px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            margin-left: 6px;\r\n");
      out.write("            line-height: 100em;\r\n");
      out.write("            vertical-align: top;\r\n");
      out.write("            background: url('');\r\n");
      out.write("            -webkit-background-size: 30px;\r\n");
      out.write("            background-size: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-ex9067 {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            width: 1px;\r\n");
      out.write("            height: 1px;\r\n");
      out.write("            font-size: 1px;\r\n");
      out.write("            line-height: 100px;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .css-307cmn {\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 30px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            margin-left: 6px;\r\n");
      out.write("            line-height: 100em;\r\n");
      out.write("            vertical-align: top;\r\n");
      out.write("            background: url('https://img.29cm.co.kr/next-next_attach/2023/02/14/7eb922eab8794352a0e26f701a4730a7_20230214020512.png');\r\n");
      out.write("            -webkit-background-size: 30px;\r\n");
      out.write("            background-size: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-1e0olgk {\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 30px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            margin-left: 6px;\r\n");
      out.write("            line-height: 100em;\r\n");
      out.write("            vertical-align: top;\r\n");
      out.write("            background: url('https://img.29cm.co.kr/next-next_attach/2023/02/14/be0d982f48f748c489e81247df619681_20230214020602.png');\r\n");
      out.write("            -webkit-background-size: 30px;\r\n");
      out.write("            background-size: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-1jjk5h4 {\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 30px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            margin-left: 6px;\r\n");
      out.write("            line-height: 100em;\r\n");
      out.write("            vertical-align: top;\r\n");
      out.write("            background: url('https://img.29cm.co.kr/next-next_attach/2023/02/14/47fffa1ac78348d9a7b6de7c64f30510_20230214020617.png');\r\n");
      out.write("            -webkit-background-size: 30px;\r\n");
      out.write("            background-size: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .css-187qk54 {\r\n");
      out.write("            display: table;\r\n");
      out.write("            table-layout: fixed;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            min-height: 160px;\r\n");
      out.write("            margin-top: 17px;\r\n");
      out.write("            padding: 9px 0 6px;\r\n");
      out.write("            border-top: 1px solid #e4e4e4;\r\n");
      out.write("        }\r\n");
      out.write("        .css-kaepde {\r\n");
      out.write("            float: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-kaepde::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            clear: both;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-1utwm2c {\r\n");
      out.write("            float: left;\r\n");
      out.write("            margin-right: 6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-xsdkei {\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("            padding-right: 103px;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            line-height: 26px;\r\n");
      out.write("            color: #303033;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-1lznoou {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-top: 2px;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            line-height: 24px;\r\n");
      out.write("            color: #303033;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-19fflyl {\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            padding-right: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-7wha64 {\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            line-height: 26px;\r\n");
      out.write("            color: #303033;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-5ttnht {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding: 0 200px 50px 0;\r\n");
      out.write("            border-top: 1px solid #e4e4e4;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-ixasrx {\r\n");
      out.write("            display: -webkit-box;\r\n");
      out.write("            display: -webkit-flex;\r\n");
      out.write("            display: -ms-flexbox;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            -webkit-align-items: center;\r\n");
      out.write("            -webkit-box-align: center;\r\n");
      out.write("            -ms-flex-align: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 42px;\r\n");
      out.write("            right: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .css-100q4rc {\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 42px;\r\n");
      out.write("            height: 42px;\r\n");
      out.write("            line-height: 100em;\r\n");
      out.write("            vertical-align: top;\r\n");
      out.write("            background: url('https://img.29cm.co.kr/next29cm/sp_pc_footer.jpg');\r\n");
      out.write("            -webkit-background-position: 0 -27px;\r\n");
      out.write("            background-position: 0 -27px;\r\n");
      out.write("            -webkit-background-size: 162px 69px;\r\n");
      out.write("            background-size: 162px 69px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-y9tiu2 {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 1px;\r\n");
      out.write("            height: 1px;\r\n");
      out.write("            padding-left: 8px;\r\n");
      out.write("            font-size: 11px;\r\n");
      out.write("            line-height: 16px;\r\n");
      out.write("            color: #999;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .css-1k3wlg9 {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding-left: 8px;\r\n");
      out.write("            font-size: 11px;\r\n");
      out.write("            line-height: 16px;\r\n");
      out.write("            color: #999;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-14jjk0p {\r\n");
      out.write("            margin: 12px 0 4px;\r\n");
      out.write("            font-size: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-ldr47f {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-left: 8px;\r\n");
      out.write("            padding: 0 7px;\r\n");
      out.write("            line-height: 20px;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            background: #a4a4a4;\r\n");
      out.write("        }\r\n");
      out.write("        .css-1saj6ln {\r\n");
      out.write("            font-size: 10px;\r\n");
      out.write("            line-height: 24px;\r\n");
      out.write("            color: #5d5d5d;\r\n");
      out.write("        }\r\n");
      out.write("        .css-1odwksc {\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        .css-1x8o338 {\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        .css-vsq8xl {\r\n");
      out.write("            float: left;\r\n");
      out.write("            padding-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .css-162o57p {\r\n");
      out.write("            content: '';\r\n");
      out.write("            clear: both;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        .css-pyoqt1 {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            line-height: 22px;\r\n");
      out.write("            color: #000000;\r\n");
      out.write("            -webkit-text-decoration: none;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .css-pyoqt1:not(:last-of-type)::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 1px;\r\n");
      out.write("            height: 11px;\r\n");
      out.write("            margin: -1px 10px 1px;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            background: #d4d4d4;\r\n");
      out.write("        }\r\n");
      out.write("        .css-1w8ypd0 {\r\n");
      out.write("		    overflow: hidden;\r\n");
      out.write("		    display: inline-block;\r\n");
      out.write("		    max-width: 98%;\r\n");
      out.write("		    font-size: 12px;\r\n");
      out.write("		    font-weight: normal;\r\n");
      out.write("		    line-height: 22px;\r\n");
      out.write("		    color: rgb(48, 48, 51);\r\n");
      out.write("		    text-decoration: none;\r\n");
      out.write("		    text-overflow: ellipsis;\r\n");
      out.write("		    white-space: nowrap;\r\n");
      out.write("		}\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"\">                  \r\n");
      out.write("<footer class=\"css-1lo70d e1l4oco10\">\r\n");
      out.write("    <div class=\"css-6936h5 e1l4oco11\">\r\n");
      out.write("        <section class=\"css-6936h5 ettxrej0\">\r\n");
      out.write("            <div><span class=\"css-dbdgx9 e1q77p0w0\" color=\"primary\">고객 센터 <!-- -->1644-0560</span><span\r\n");
      out.write("                    class=\"css-3x9huk e1q77p0w0\" color=\"tertiary\">운영시간 : 평일 <!-- -->10:00 ~ 17:00<!-- --> (점심시간\r\n");
      out.write("                    <!-- -->12:30 ~ 13:30<!-- --> 제외 / 주말 및 공휴일 제외)</span></div>\r\n");
      out.write("            <div class=\"css-k008qs ettxrej1\">\r\n");
      out.write("                <a class=\"css-bs7ejj ettxrej2\" style=\"color: white\" href=\"#\">FAQ \r\n");
      out.write("                    <svg class=\"ettxrej3 css-1tfgiui e15lsifv0\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 42 80\" >\r\n");
      out.write("                        <path d=\"M1 0l40 40.083L1.166 80\" fill=\"none\" fill-rule=\"evenodd\" stroke=\"#000000\" stroke-width=\"5\" ></path>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"css-bs7ejj ettxrej2\" style=\"color: white\" href=\"#\">1:1 문의 \r\n");
      out.write("                    <svg class=\"ettxrej3 css-1tfgiui e15lsifv0\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 42 80\">\r\n");
      out.write("                        <path d=\"M1 0l40 40.083L1.166 80\" fill=\"none\" fill-rule=\"evenodd\" stroke=\"#000000\" stroke-width=\"5\"></path>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"css-1xit630 ejsdwyr0\">\r\n");
      out.write("            <a class=\"css-1y0tu78 ejsdwyr1\" target=\"_blank\" href=\"https://www.instagram.com/29cm.official/\">\r\n");
      out.write("                <div class=\"css-ex9067 ejsdwyr2\">instagram</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"css-307cmn ejsdwyr1\" target=\"_blank\" href=\"https://www.youtube.com/@29CM\">\r\n");
      out.write("                <div class=\"css-ex9067 ejsdwyr2\">youtube</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"css-1e0olgk ejsdwyr1\" target=\"_blank\" href=\"https://apps.apple.com/us/app/29cm/id789634744\">\r\n");
      out.write("                <div class=\"css-ex9067 ejsdwyr2\">29CM iOS app download</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"css-1jjk5h4 ejsdwyr1\" target=\"_blank\" href=\"https://play.google.com/store/apps/details?id=com.the29cm.app29cm\">\r\n");
      out.write("                <div class=\"css-ex9067 ejsdwyr2\">29CM Android app download</div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"css-187qk54 e1l4oco12\">\r\n");
      out.write("        <ul class=\"css-kaepde e1l4oco13\">\r\n");
      out.write("            <li class=\"css-1utwm2c e1t68iwn0\" >\r\n");
      out.write("                <h2 class=\"css-xsdkei e1t68iwn1\">ABOUT US</h2><a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\"\r\n");
      out.write("                    href=\"#\">29CM 소개</a><a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\"\r\n");
      out.write("                    href=\"#\">인재채용</a><a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\"\r\n");
      out.write("                    href=\"#\">상시 할인 혜택</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"css-1utwm2c e1t68iwn0\">\r\n");
      out.write("                <h2 class=\"css-xsdkei e1t68iwn1\">MY ORDER</h2>\r\n");
      out.write("                <a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\" href=\"#\">주문배송</a>\r\n");
      out.write("                <a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\" href=\"#\">취소/교환/반품 내역</a>\r\n");
      out.write("                <a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\" href=\"#\">상품리뷰내역</a>\r\n");
      out.write("                <a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\" href=\"#\">증빙서류발급</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"css-1utwm2c e1t68iwn0\">\r\n");
      out.write("                <h2 class=\"css-xsdkei e1t68iwn1\">MY ACCOUNT</h2><a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\"\r\n");
      out.write("                    href=\"#\">회원정보수정</a><a\r\n");
      out.write("                    class=\"css-1lznoou e1t68iwn2\" style=\"color: black\" href=\"#\">회원등급</a><a\r\n");
      out.write("                    class=\"css-1lznoou e1t68iwn2\" style=\"color: black\" href=\"#\">마일리지현황</a><a\r\n");
      out.write("                    class=\"css-1lznoou e1t68iwn2\" style=\"color: black\" href=\"#\">쿠폰</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"css-1utwm2c e1t68iwn0\">\r\n");
      out.write("                <h2 class=\"css-xsdkei e1t68iwn1\">HELP</h2>\r\n");
      out.write("                <a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\" href=\"inquiry/inquiry.do\">1:1 상담내역</a>\r\n");
      out.write("                <a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\" href=\"#\">마케팅 제휴, 입점, 대량 주문 문의</a>\r\n");
      out.write("                <a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\" href=\"#\">상품 Q&amp;A내역</a>\r\n");
      out.write("                <a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\" href=\"/noticeBoard/notice.do\">공지사항</a>\r\n");
      out.write("                <a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\" href=\"#\">FAQ</a>\r\n");
      out.write("                <a class=\"css-1lznoou e1t68iwn2\" style=\"color: black\" href=\"#\">고객의 소리</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"css-19fflyl elmic6g0\">\r\n");
      out.write("            <h2 class=\"css-7wha64 elmic6g1\">NOTICE</h2>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"css-8b30vy elmic6g2\">\r\n");
      out.write("                    <a class=\"css-1w8ypd0 elmic6g3\" style=\"color: black\" href=\"#\">[공지] 29CM 서비스 이용약관 개정 사전 안내 (시행일: 2024년 5월 20일)</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"css-8b30vy elmic6g2\">\r\n");
      out.write("                    <a class=\"css-1w8ypd0 elmic6g3\" style=\"color: black\" href=\"#\">[공지] 5월 고객센터 운영 안내</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"css-8b30vy elmic6g2\">\r\n");
      out.write("                    <a class=\"css-1w8ypd0 elmic6g3\" style=\"color: black\" href=\"#\">[공지] 개인정보 처리방침 개정 안내 (시행일 : 2024년 4월 30일)</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"css-8b30vy elmic6g2\">\r\n");
      out.write("                    <a class=\"css-1w8ypd0 elmic6g3\" style=\"color: black\" href=\"#\">[공지] 29CM 구매확정 기준 정책 변경 안내 (시행일 : 2024년 4월 1일)</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"css-8b30vy elmic6g2\">\r\n");
      out.write("                    <a class=\"css-1w8ypd0 elmic6g3\" style=\"color: black\" href=\"#\">[공지] 개인 식별 정보(CI) 수집을 위한 본인인증 서비스 시행 안내</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <section class=\"css-5ttnht e978fir0\">\r\n");
      out.write("        <div class=\"e978fir1 css-ixasrx e13td8480\">\r\n");
      out.write("            <a class=\"css-100q4rc e13td8481\" href=\"https://mark.inicis.com/mark/escrow_popup.php?mid=MOIAplusBP\">\r\n");
      out.write("                <span class=\"css-y9tiu2 e13td8483\">이니시스 결제시스템 유효성 확인</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <span class=\"css-1k3wlg9 e13td8482\">KG 에스크로<br>가입 사실 확인</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"css-14jjk0p e1nr05730\">\r\n");
      out.write("            <a class=\"css-pyoqt1 e1nr05731\" href=\"https://www.29cm.co.kr/home/private\" style=\"color: black\"><strong>개인정보처리방침</strong></a>\r\n");
      out.write("            <a class=\"css-pyoqt1 e1nr05731\" href=\"https://www.29cm.co.kr/home/agreement\" style=\"color: black\">이용약관</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"css-1saj6ln eiz30az0\">\r\n");
      out.write("            <div class=\"css-162o57p eiz30az1\">\r\n");
      out.write("                <dl class=\"css-1odwksc eiz30az3\">\r\n");
      out.write("                    <dt class=\"css-1x8o338 eiz30az4\">상호명</dt>\r\n");
      out.write("                    <dd class=\"css-vsq8xl eiz30az5\">(주)무신사</dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <dl class=\"css-1odwksc eiz30az3\">\r\n");
      out.write("                    <dt class=\"css-1x8o338 eiz30az4\">사업장소재지</dt>\r\n");
      out.write("                    <dd class=\"css-vsq8xl eiz30az5\">서울특별시 성동구 아차산로 13길 11, 1층 (성수동2가, 무신사캠퍼스 엔1)</dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <dl class=\"css-1odwksc eiz30az3\">\r\n");
      out.write("                    <dt class=\"css-1x8o338 eiz30az4\">팩스</dt>\r\n");
      out.write("                    <dd class=\"css-vsq8xl eiz30az5\">070-8622-7737</dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <dl class=\"css-1odwksc eiz30az3\">\r\n");
      out.write("                    <dt class=\"css-1x8o338 eiz30az4\" >사업자등록번호</dt>\r\n");
      out.write("                    <dd class=\"css-vsq8xl eiz30az5\">211-88-79575</dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <dl class=\"css-1odwksc eiz30az3\">\r\n");
      out.write("                    <dt class=\"css-1x8o338 eiz30az4\">통신판매업신고</dt>\r\n");
      out.write("                    <dd class=\"css-vsq8xl eiz30az5\">2022-서울성동-01952\r\n");
      out.write("                        <a class=\"css-ldr47f eiz30az7\" target=\"_blank\" href=\"https://www.ftc.go.kr/bizCommPop.do?wrkr_no=2118879575&amp;apv_perm_no=\" style=\"color: white\">사업자정보확인</a>\r\n");
      out.write("                    </dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"css-162o57p eiz30az1\">\r\n");
      out.write("                <dl class=\"css-1odwksc eiz30az3\">\r\n");
      out.write("                    <dt class=\"css-1x8o338 eiz30az4\">전화번호</dt>\r\n");
      out.write("                    <dd class=\"css-vsq8xl eiz30az5\"><a class=\"css-vcptzx eiz30az6\" style=\"color: black\"\r\n");
      out.write("                            href=\"tel:1644-0560\">1644-0560</a></dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <dl class=\"css-1odwksc eiz30az3\">\r\n");
      out.write("                    <dt class=\"css-1x8o338 eiz30az4\">이메일</dt>\r\n");
      out.write("                    <dd class=\"css-vsq8xl eiz30az5\"><a class=\"css-vcptzx eiz30az6\" style=\"color: black\"\r\n");
      out.write("                            href=\"mailto:customer@29cm.co.kr\">customer@29cm.co.kr</a></dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <dl class=\"css-1odwksc eiz30az3\">\r\n");
      out.write("                    <dt class=\"css-1x8o338 eiz30az4\">대표이사</dt>\r\n");
      out.write("                    <dd class=\"css-vsq8xl eiz30az5\">조만호, 박준모, 한문일</dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <dl class=\"css-1odwksc eiz30az3\">\r\n");
      out.write("                    <dt class=\"css-1x8o338 eiz30az4\">개인정보 보호책임자</dt>\r\n");
      out.write("                    <dd class=\"css-vsq8xl eiz30az5\">정광은</dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <dl class=\"css-1odwksc eiz30az3\">\r\n");
      out.write("                    <dt class=\"css-1x8o338 eiz30az4\">호스팅서비스</dt>\r\n");
      out.write("                    <dd class=\"css-vsq8xl eiz30az5\">(주)무신사</dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"css-162o57p eiz30az1\">\r\n");
      out.write("                <p class=\"css-1tmlw65 eiz30az2\">일부 상품의 경우 29CM는 통신판매의 당사자가 아닌 통신판매중개자로서 상품, 상품정보, 거래에 대한 책임이 제한될\r\n");
      out.write("                    수 있으므로, 각 상품 페이지에서 구체적인 내용을 확인하시기 바랍니다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</footer> \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
